package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.triggers.ScheduleTrigger
import jetbrains.buildServer.configs.kotlin.v2019_2.triggers.schedule
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'First'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("First")) {
    triggers {
        val trigger1 = find<ScheduleTrigger> {
            schedule {
                schedulingPolicy = cron {
                    seconds = "35"
                    minutes = "0"
                    hours = "16"
                    dayOfMonth = "*"
                    dayOfWeek = "*"
                    month = "*"
                    year = "*"
                }
                branchFilter = "+:master"
                triggerBuild = always()
                withPendingChangesOnly = false
            }
        }
        trigger1.apply {
            schedulingPolicy = cron {
                seconds = "35"
                minutes = "1"
                hours = "*"
                dayOfMonth = "*"
                dayOfWeek = "*"
                month = "*"
                year = "*"
                timezone = "SERVER"
            }
        }
    }
}
